api/urls.py
from django.conf.urls import include, url
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'groups', views.GroupViewSet)
router.register(r'buildings', views.BuildingViewSet)
router.register(r'rooms', views.RoomViewSet)
router.register(r'disciplines', views.DisciplineViewSet)
router.register(r'teachers', views.TeacherViewSet)
router.register(r'lessons', views.LessonViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

frontend/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views, ajax_views

urlpatterns = [
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<type>groups|teachers|rooms)/(?P<id>[0-9]+)/$', views.timetable, name='timetable'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^api/$', views.api, name='api'),
    url(r'^(?P<type>groups|teachers|rooms|disciplines)/search/$', ajax_views.search, name='search'),
    url(r'^edit-profile/$', ajax_views.edit_profile, name='edit_profile'),
    url(r'^create-lesson/$', ajax_views.create_lesson, name='create_lesson'),
    url(r'^edit-lesson/$', ajax_views.edit_lesson, name='edit_lesson'),
    url(r'^remove-lesson/$', ajax_views.remove_lesson, name='remove_lesson'),
    url(r'^link-lesson/$', ajax_views.link_lesson, name='link_lesson'),
    url(r'^login/$', ajax_views.auth_login, name='login'),
    url(r'^logout/$', ajax_views.auth_logout, name='logout'),
    url(r'^admin/', include(admin.site.urls))
]

handler400 = 'frontend.views.error400'
handler403 = 'frontend.views.error403'
handler404 = 'frontend.views.error404'
handler500 = 'frontend.views.error500'

frontend/models.py
from django.db import models
from django.contrib.auth.models import User
from data.models import Group, Teacher

class UnregisteredVKUserTimetablePermissions(models.Model):
    vk_user_id = models.IntegerField()
    groups = models.ManyToManyField(Group, blank=True)
    teachers = models.ManyToManyField(Teacher, blank=True)

    def groups_str(self):
        str = ''
        for i, group in enumerate(self.groups.all()):
            str += group.name
            if i < self.groups.all().count() - 1:
                str += ', '
        return str

    def teachers_str(self):
        str = ''
        for i, teacher in enumerate(self.teachers.all()):
            str += teacher.short_name()
            if i < self.teachers.all().count() - 1:
                str += ', '
        return str

frontend/forms.py
import json
import urllib.request
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from data.models import Group, Teacher
from .models import UnregisteredVKUserTimetablePermissions

class EditUserProfile(forms.ModelForm):
    username = forms.CharField(required=True, min_length=5, max_length=30)
    new_password = forms.CharField(required=False, min_length=8, max_length=32, widget=forms.PasswordInput)
    new_password_confirm = forms.CharField(required=False, widget=forms.PasswordInput)
    old_password = forms.CharField(required=True, widget=forms.PasswordInput)

    def clean_new_password_confirm(self):
        if self.cleaned_data.get('new_password') or self.cleaned_data.get('new_password_confirm'):
            if not (self.cleaned_data.get('new_password') and self.cleaned_data.get('new_password_confirm')):
                raise ValidationError(_('Passwords don\'t match'))
            if self.cleaned_data['new_password'] != self.cleaned_data['new_password_confirm']:
                raise ValidationError(_('Passwords don\'t match'))

    def clean_old_password(self):
        if not self.instance.check_password(self.cleaned_data['old_password']):
            raise ValidationError(_('Wrong password'))

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.cleaned_data.get('new_password'):
            instance.set_password(self.cleaned_data['new_password'])
        if commit:
            instance.save()
        return instance

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'new_password', 'new_password_confirm', 'email', 'old_password']

class AddVKUserPermissions(forms.Form):
    identifier = forms.CharField(label='ID, link or username', max_length=100)
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=False)
    teachers = forms.ModelMultipleChoiceField(queryset=Teacher.objects.all(), required=False)

    def clean_identifier(self):
        identifier_str = self.cleaned_data['identifier']

        if (identifier_str.find('/') != -1):
            identifier_str = identifier_str.split('/')[-1]

        api_data = json.loads(urllib.request.urlopen('https://api.vk.com/method/users.get?user_ids={0}&v=5.40'.format(identifier_str)).read().decode('utf-8'))
        if ('response' not in api_data) or (len(api_data['response']) == 0):
            raise ValidationError(_('No such user registered in VK'))

        return str(api_data['response'][0]['id'])

    class Meta:
        fields = ['identifier', 'groups', 'teachers']

api/views.py
from rest_framework import viewsets, pagination, filters
from rest_framework.response import Response
from rest_framework.decorators import detail_route
from data.models import *
from . import serializers
from .filters import *

class GlobalViewPagination(pagination.LimitOffsetPagination):
    default_limit = 10
    max_limit = 100

def timetable(request, lessons):
    result = {}
    result['data'] = {}
    
    for week_choice in Lesson.WEEK_CHOICES:
        for day_choice in Lesson.DAY_CHOICES:
            for number_choice in Lesson.NUMBER_CHOICES:
                if lessons.filter(week=week_choice[0], day=day_choice[0], number=number_choice[0]).exists():
                    if week_choice[0] not in result['data'].keys():
                        result['data'][week_choice[0]] = {}
                    if day_choice[0] not in result['data'][week_choice[0]].keys():
                        result['data'][week_choice[0]][day_choice[0]] = {}

                    result_day = result['data'][week_choice[0]][day_choice[0]]

                    lesson = lessons.get(week=week_choice[0], day=day_choice[0], number=number_choice[0])
                    lesson_serializer = serializers.NestedLessonSerializer(lesson, context={'request': request})
                    result_day[number_choice[0]] = lesson_serializer.data

    return Response(result)

class GroupViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Group.objects.all()
    serializer_class = serializers.GroupSerializer
    pagination_class = GlobalViewPagination

    filter_backends = (SearchGroupFilterBackend, filters.DjangoFilterBackend)
    filter_fields = ('name', 'okr', 'type')

    @detail_route(methods=['GET'])
    def timetable(self, request, pk, format=None):
        return timetable(request, Lesson.objects.filter(groups=Group.objects.get(pk=pk)))

class BuildingViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Building.objects.all()
    serializer_class = serializers.BuildingSerializer
    pagination_class = GlobalViewPagination

class RoomViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Room.objects.all()
    serializer_class = serializers.RoomSerializer
    pagination_class = GlobalViewPagination

    filter_backends = (SearchRoomFilterBackend, filters.DjangoFilterBackend)
    filter_fields = ('name', 'building')

    @detail_route(methods=['GET'])
    def timetable(self, request, pk, format=None):
        return timetable(request, Lesson.objects.filter(rooms=Room.objects.get(pk=pk)))

class DisciplineViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Discipline.objects.all()
    serializer_class = serializers.DisciplineSerializer
    pagination_class = GlobalViewPagination

    filter_backends = (SearchDisciplineFilterBackend,)

class TeacherViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Teacher.objects.all()
    serializer_class = serializers.TeacherSerializer
    pagination_class = GlobalViewPagination

    filter_backends = (SearchTeacherFilterBackend, filters.DjangoFilterBackend)
    filter_fields = ('last_name', 'first_name', 'middle_name', 'degree')

    @detail_route(methods=['GET'])
    def timetable(self, request, pk, format=None):
        return timetable(request, Lesson.objects.filter(teachers=Teacher.objects.get(pk=pk)))

class LessonViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Lesson.objects.all()
    serializer_class = serializers.LessonSerializer
    pagination_class = GlobalViewPagination

    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('number', 'day', 'week', 'type', 'discipline', 'groups', 'teachers', 'rooms')

frontend/views.py
import json
import urllib.request
import urllib.parse
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie
from django.core.exceptions import PermissionDenied
from django.conf import settings
from data.models import *
from .forms import EditUserProfile
from .page_cache import get_timetable_cache

page_base_title = 'Розклад КПІ'

def check_captcha(captcha_response):
    captcha_data = bytes(urllib.parse.urlencode({
        'secret': settings.GOOGLE_RECAPTCHA_PRIVATE,
        'response': captcha_response,
    }).encode())
    return json.loads(urllib.request.urlopen('https://www.google.com/recaptcha/api/siteverify', captcha_data).read().decode('utf-8'))['success']

@ensure_csrf_cookie
def error400(request):
    return render(request, 'error.html', {
        'title': page_base_title + ' | 400',
        'error_text': '400',
        'error_text2': 'Bad Request',
    }, status=400)

@ensure_csrf_cookie
def error403(request):
    return render(request, 'error.html', {
        'title': page_base_title + ' | 403',
        'error_text': '403',
        'error_text2': 'Forbidden',
    }, status=403)

@ensure_csrf_cookie
def error404(request):
    return render(request, 'error.html', {
        'title': page_base_title + ' | 404',
        'error_text': '404',
        'error_text2': 'Нажаль, такої сторінки не існує',
    }, status=404)

@ensure_csrf_cookie
def error500(request):
    return render(request, 'error.html', {
        'title': page_base_title + ' | 500',
        'error_text': '500',
        'error_text2': 'Server Error',
    }, status=500)

@ensure_csrf_cookie
def index(request):
    context = {}
    context['title'] = page_base_title
    
    return render(request, 'index.html', context)

@ensure_csrf_cookie
def api(request):
    context = {}
    context['title'] = page_base_title + ' | API'
    context['api_domain'] = settings.API_DOMAIN
    
    return render(request, 'api.html', context)

@ensure_csrf_cookie
def profile(request):
    if not request.user.is_authenticated():
        raise PermissionDenied
    if request.user.social_auth.all().count() > 0:
        raise PermissionDenied

    context = {}
    context['user_form'] = EditUserProfile(instance=request.user)
    context['title'] = page_base_title + ' | Редагування аккаунту'

    return render(request, 'profile.html', context)

@ensure_csrf_cookie
def timetable(request, type, id):
    context = {}

    context['id'] = id
    context['type'] = type
    context['top_menu_str'] = ''

    if type == 'groups':
        if not Group.objects.filter(id=id).exists():
            raise Http404()
        context['top_menu_str'] = Group.objects.get(id=id).name.upper()
    elif type == 'teachers':
        if not Teacher.objects.filter(id=id).exists():
            raise Http404()
        context['top_menu_str'] = Teacher.objects.get(id=id).name().upper()
    else:
        if not Room.objects.filter(id=id).exists():
            raise Http404()
        context['top_menu_str'] = Room.objects.get(id=id).full_name().upper()
    context['title'] = 'Розклад КПІ | ' + context['top_menu_str']

    queryset = None
    if type == 'groups':
        queryset = Lesson.objects.filter(groups=Group.objects.get(id=id))
    elif type == 'teachers':
        queryset = Lesson.objects.filter(teachers=Teacher.objects.get(id=id))
    else:
        queryset = Lesson.objects.filter(rooms=Room.objects.get(id=id))

    if ((type == 'groups' and (request.user.has_perm('edit_group_timetable', Group.objects.get(id=id)) or request.user.has_perm('data.edit_group_timetable'))) or
        (type == 'teachers' and (request.user.has_perm('edit_teacher_timetable', Teacher.objects.get(id=id)) or request.user.has_perm('data.edit_teacher_timetable')))):
        
        initial_data = {}
        initial_data['groups'] = []
        initial_data['teachers'] = []
        initial_data['rooms'] = []
        initial_data['disciplines'] = []
        for lesson in queryset:
            for group in lesson.groups.all():
                group_dict = {
                    'id': group.id,
                    'name': group.name,
                }

                if group_dict not in initial_data['groups']:
                    initial_data['groups'].append(group_dict)

            for teacher in lesson.teachers.all():
                teacher_dict = {
                    'id': teacher.id,
                    'name': teacher.name(),
                }

                if teacher_dict not in initial_data['teachers']:
                    initial_data['teachers'].append(teacher_dict)

            for room in lesson.rooms.all():
                room_dict = {
                    'id': room.id,
                    'name': room.full_name(),
                }

                if room_dict not in initial_data['rooms']:
                    initial_data['rooms'].append(room_dict)
        
            discipline_dict = {
                'id': lesson.discipline.id,
                'name': lesson.discipline.name,
            }

            if discipline_dict not in initial_data['disciplines']:
                initial_data['disciplines'].append(discipline_dict)

        context['initial_data'] = json.dumps(initial_data)

        context['timetable'] = []

        for week_choice in Lesson.WEEK_CHOICES:
            week = week_choice[0] - 1
            context['timetable'].append([])

            for day_choice in Lesson.DAY_CHOICES:
                day = day_choice[0] - 1
                context['timetable'][week].append([])

                for number_choice in Lesson.NUMBER_CHOICES:
                    number = number_choice[0] - 1

                    if queryset.filter(week=week + 1, day=day + 1, number=number + 1).exists():
                        context['timetable'][week][day].append(queryset.get(week=week + 1, day=day + 1, number=number + 1))
                    else:
                        context['timetable'][week][day].append(None)

        return render(request, 'timetable_edit.html', context)
    else:
        if queryset.count() == 0:
            context['error_text'] = 'Нажаль, розклад відсутній :('
            context['error_text2'] = 'Зверніться до адміністраторів'

            return render(request, 'error.html', context)

        if not get_timetable_cache(type, id):
            context['timetable'] = []

            for week_choice in Lesson.WEEK_CHOICES:
                week = week_choice[0] - 1
                context['timetable'].append([])

                for day_choice in Lesson.DAY_CHOICES:
                    day = day_choice[0] - 1
                    context['timetable'][week].append([])

                    for number_choice in Lesson.NUMBER_CHOICES:
                        number = number_choice[0] - 1

                        if queryset.filter(week=week + 1, day=day + 1, number=number + 1).exists():
                            lesson = queryset.get(week=week + 1, day=day + 1, number=number + 1)

                            for i in range(len(context['timetable'][week][day]), number):
                                context['timetable'][week][day].append(None)

                            context['timetable'][week][day].append(lesson)

        return render(request, 'timetable.html', context)

frontend/templates/error.html
{% extends 'base.html' %}

{% block content %}
	<section id="error-block">
		<div class="container">
			<h1>Ой! Щось пішло не так!</h1>
			<h3>{{ error_text }}</h3>
			<p>{{ error_text2 }}</p>
			<p><button class="button"  onclick="location.href = '{% url 'index' %}'">повернутися на головну</button></p>
			<div class="panda">
				<span class="eyes">
					<span class="eye left"><span class="ball"></span></span>
					<span class="eye right"><span class="ball"></span></span>
				</span>
				<span class="nose"></span>
				<span class="mouth"></span>
				<span class="ear left"></span>
				<span class="ear right"></span>
			</div>
		</div>
	</section>
	<style>
		body{
			overflow: hidden;
		}
		/* mixins */
		/* extends */
		.circle, .panda, .panda .eyes .eye .ball, .panda .nose, .panda .ear {
		  -moz-border-radius: 100%;
		  -webkit-border-radius: 100%;
		  border-radius: 100%;
		}

		.panda {
			text-align: left;
			position: relative;
			background-color: white;
			border: 12px solid black;
			width: 300px;
			height: 300px;
			top: 50%;
			left: 50%;
			margin-left: -162px;
			margin-top: 70px;
			-webkit-animation: bounce .85s infinite;
			-moz-animation: bounce .85s infinite;
			animation: bounce .85s infinite;
		}
		.panda .eyes {
			width: 100%;
			position: absolute;
			top: 55%;
			height: 57.5px;
			margin-top: -28.75px;
		}
		.panda .eyes .eye {
			position: absolute;
			width: 115px;
			height: 57.5px;
			background-color: black;
			overflow: hidden;
			-moz-border-radius: 0 0 115px 115px;
			-webkit-border-radius: 0;
			border-radius: 0 0 115px 115px;
		}
		.panda .eyes .eye.left {
			left: 10px;
			-moz-transform: rotate(30deg);
			-ms-transform: rotate(30deg);
			-webkit-transform: rotate(30deg);
			transform: rotate(30deg);
		}
		.panda .eyes .eye.right {
			right: 10px;
			-moz-transform: rotate(-30deg);
			-ms-transform: rotate(-30deg);
			-webkit-transform: rotate(-30deg);
			transform: rotate(-30deg);
		}
		.panda .eyes .eye .ball {
			position: absolute;
			width: 30px;
			height: 30px;
			top: 50%;
			margin-top: -27px;
			left: 50%;
			margin-left: -27px;
			top: 0px;
			background-color: black;
			border: 12px solid white;
		}
		.panda .eyes .eye.left .ball {
			left: 55%;
		}
		.panda .eyes .eye.right .ball {
			left: 45%;
		}
		.panda .nose {
			position: absolute;
			width: 16px;
			height: 16px;
			top: 50%;
			margin-top: -8px;
			left: 50%;
			margin-left: -8px;
			margin-top: 31px;
			background-color: black;
		}
		.panda .mouth {
			background-color: black;
			width: 50px;
			height: 10px;
			position: absolute;
			left: 50%;
			margin-left: -33.33333px;
			top: 75%;
			-moz-border-radius: 10px;
			-webkit-border-radius: 10px;
			border-radius: 10px;
		}
		.panda .ear {
			background-color: black;
			position: absolute;
			z-index: -1;
			top: -30px;
			width: 130px;
			height: 130px;
		}
		.panda .ear.left {
			left: -35px;
		}
		.panda .ear.right {
			right: -35px;
		}

		@-webkit-keyframes bounce {
			0% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
			25% {
				top: 55%;
				left: 51%;
				padding-top: 20px;
				padding-left: 2px;
			}
			50% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
			75% {
				top: 55%;
				left: 49%;
				padding-top: 20px;
				padding-right: 2px;
			}
			100% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
		}
		@-moz-keyframes bounce {
			0% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
			25% {
				top: 55%;
				left: 51%;
				padding-top: 20px;
				padding-left: 2px;
			}
			50% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
			75% {
				top: 55%;
				left: 49%;
				padding-top: 20px;
				padding-right: 2px;
			}
			100% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
		}
		@keyframes bounce {
			0% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
			25% {
				top: 55%;
				left: 51%;
				padding-top: 20px;
				padding-left: 2px;
			}
			50% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
			75% {
				top: 55%;
				left: 49%;
				padding-top: 20px;
				padding-right: 2px;
			}
			100% {
				top: 50%;
				left: 50%;
				padding-top: 0px;
				padding-left: 0px;
			}
		}
	</style>
{% endblock %}

frontend/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div id="index_block" class="container">
	<h1 class="title">Вітаємо на Новому Розкладі КПІ!</h1>
	<div id="shield" class="one_half"></div>
	<p class="one_half last">Відтепер ти матимеш доступ до актуального онлайн-розкладу завжди! <br><br>А якщо щось не співпадає, то мершій штовхай свого старосту, щоб той швиденько все змінив.<br><br>Якщо ти староста, або викладач, то пиши <a href="http://goo.gl/forms/ZXQ0Nh9HAc" target="_blank">сюди</a> і ми надамо тобі доступ!<br><br>Наразі цей розклад працює у режимі бета-тестування, тому ми будемо вдячні приймати будь-які ваші відгуки</p>
	<div class="clear"></div>
</div>
<style>
	.background, body{
		background-color: #fcfcfc;;
		color: #000;
	}
</style>
{% endblock %}

frontend/templates/profile.html
{% extends 'base.html' %}

{% block content %}
	<section id="profile-settings">
		<div class="container">
			<form action="{% url 'edit_profile' %}" method="post" id="profile_edit_form">
				<h2 class="title">Редагування аккаунту</h2>
				<div class="one_half">
					<h3>Змінити логін: </h3>
					<p class="hint">
						- тількі цифри та латинські літери
						<br>
						- від 5 до 30 символів
					</p>
					<div class="content">
						<p>
							{{ user_form.username.label_tag }}
							{{ user_form.username }}
							<span class="error" id="id_username_error" data-form_name="username">Error</span>
						</p>
					</div>
				</div>
				<div class="one_half last">
					<h3>Редагування персональних даних:</h3>
					<div class="content">
						<p>
							{{ user_form.first_name.label_tag }}
							{{ user_form.first_name }}
							<span class="error" id="id_first_name_error" data-form_name="first_name">Error</span>
						</p>
						<p>
							{{ user_form.last_name.label_tag }}
							{{ user_form.last_name }}
							<span class="error" id="id_last_name_error" data-form_name="last_name">Error</span>
						</p>
					</div>
				</div>
				<div class="clear"></div>
				<div class="one_half">
					<h3>Змінити пароль: </h3>
					<p class="hint">від 8 до 32 символів</p>
					<div class="content">
						<p>
							{{ user_form.new_password.label_tag }}
							{{ user_form.new_password }}
							<span class="error" id="id_new_password_error" data-form_name="new_password">Error</span>
						</p>
						<p>
							{{ user_form.new_password_confirm.label_tag }}
							{{ user_form.new_password_confirm }}
							<span class="error" id="id_new_password_confirm_error" data-form_name="new_password_confirm">Error</span>
						</p>
					</div>
				</div>
				<div class="one_half last">
					<h3>Змінити email:</h3>
					<div class="content">
						<p>
							{{ user_form.email.label_tag }}
							{{ user_form.email }}
							<span class="error" id="id_email_error" data-form_name="email">Error</span>
						</p>
					</div>
					<div class="et-box et-info">
						<div class="et-box-content">
							<span style="font-size: 17px;">Будьте уважні!</span>
							<br style="clear: both;">Нікому не передавайте свій логін і пароль!</p>
							</div>
						</div>
				</div>
				<div class="clear"></div>
				<h3>Введіть пароль, щоб внести зміни:</h3>
				<div class="one_half">
					<div class="content">
						<p>
							{{ user_form.old_password.label_tag }}
							{{ user_form.old_password }}
							<span class="error" id="id_old_password_error" data-form_name="old_password">Error</span>
						</p>
					</div>
				</div>
				<div class="one_half last">
					<p>
						<div class="g-recaptcha" data-sitekey="{{ google_recaptcha_public }}"></div>
						<p class="error" id="id_captcha_error" data-form_name="captcha">Error</p>
					</p>
				</div>
				<div class="clear"></div>
				<p class="success_messege" id="profile_success">Успішно збережено</p>
				<button class="button" type="submit">Зберегти</button>
				<div class="clear"></div>
			</form>
		</div>
	</section>
	<script>
		$(document).ready(function() {
			$("#profile_edit_form").on("submit", function(event) {
				event.preventDefault()

				$.ajax({
					method: $(this).attr("method"),
					url: $(this).attr("action"),
					data: $(this).serialize(),
					dataType: "json"
				}).done(function(data) {
					grecaptcha.reset()

					var have_errors = false
					var error_spans = $("#profile_edit_form span.error")
					for (var i = 0; i < error_spans.length; i++) {
						var error_span = $(error_spans[i])
						var error_name = error_span.data("form_name")

						if (typeof data.errors[error_name] != "undefined") {
							have_errors = true
							if (error_span.css("opacity") == 0) {
								error_span.text(data.errors[error_name][0])
								error_span.animate({opacity: 1}, 400)
							} else {
								error_span.animate({opacity: 0}, 400, function() {
									$(this).text(data.errors[$(this).data("form_name")][0])
									$(this).animate({opacity: 1}, 400)
								})
							}
						} else {
							if (error_span.css("opacity") == 1) {
								error_span.animate({opacity: 0}, 400)
							}
						}
					}

					if (!have_errors) {
						if ($("#id_new_password").val()) {
							location = "/"
						}

						$("#id_old_password").val("")

						$("#profile_success").animate({opacity: 1}, 400, function() {
							setTimeout(function() {
								$("#profile_success").animate({opacity: 0}, 400)
							}, 2000)
						})
					}
				})
			})
		})
	</script>
{% endblock %}